name: build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [17]
            fail-fast: true
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up JDK ${{ matrix.java }}
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: ${{ matrix.java }}
            - name: Set up CMake and Ninja
              uses: lukka/get-cmake@latest
            - name: Configure git
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
            - name: Patch and build
              run: |
                  ./patchwork build
            - name: Upload a build artifact
              uses: actions/upload-artifact@v3
              with:
                name: idk lbruh
                path: build/app/build/outputs/apk/*/*.apk
